### ISSUE TITLE
Task List - Lab#4

### ISSUE THREAD

**Issue by apurbaanik** [apurbaanik/spotifyPlaylist#1]
Task List:
- [x] Create a repository
- [x] Add topStreamedArtists.java
- [x] Create a README file with a description.
- [x] Add the input and output files.
- [x] Submit the link in MS Teams.
